export default {
  ans104: { name: "ans104@1.0", module: "dev_codec_ans104" },
  compute: { name: "compute@1.0", module: "dev_cu" },
  cache: { name: "cache@1.0", module: "dev_cache" },
  cacheviz: { name: "cacheviz@1.0", module: "dev_cacheviz" },
  cron: { name: "cron@1.0", module: "dev_cron" },
  dedup: { name: "dedup@1.0", module: "dev_dedup" },
  "delegated-compute": {
    name: "delegated-compute@1.0",
    module: "dev_delegated_compute",
  },
  faff: { name: "faff@1.0", module: "dev_faff" },
  flat: { name: "flat@1.0", module: "dev_codec_flat" },
  "genesis-wasm": { name: "genesis-wasm@1.0", module: "dev_genesis_wasm" },
  greenzone: { name: "greenzone@1.0", module: "dev_green_zone" },
  httpsig: { name: "httpsig@1.0", module: "dev_codec_httpsig" },
  hyperbuddy: { name: "hyperbuddy@1.0", module: "dev_hyperbuddy" },
  json: { name: "json@1.0", module: "dev_codec_json" },
  "json-iface": { name: "json-iface@1.0", module: "dev_json_iface" },
  "local-name": { name: "local-name@1.0", module: "dev_local_name" },
  lookup: { name: "lookup@1.0", module: "dev_lookup" },
  lua: { name: "lua@5.3a", module: "dev_lua" },
  manifest: { name: "manifest@1.0", module: "dev_manifest" },
  message: { name: "message@1.0", module: "dev_message" },
  meta: { name: "meta@1.0", module: "dev_meta" },
  monitor: { name: "monitor@1.0", module: "dev_monitor" },
  multipass: { name: "multipass@1.0", module: "dev_multipass" },
  name: { name: "name@1.0", module: "dev_name" },
  "node-process": { name: "node-process@1.0", module: "dev_node_process" },
  p4: { name: "p4@1.0", module: "dev_p4" },
  patch: { name: "patch@1.0", module: "dev_patch" },
  poda: { name: "poda@1.0", module: "dev_poda" },
  process: { name: "process@1.0", module: "dev_process" },
  push: { name: "push@1.0", module: "dev_push" },
  relay: { name: "relay@1.0", module: "dev_relay" },
  router: { name: "router@1.0", module: "dev_router" },
  scheduler: { name: "scheduler@1.0", module: "dev_scheduler" },
  "simple-pay": { name: "simple-pay@1.0", module: "dev_simple_pay" },
  snp: { name: "snp@1.0", module: "dev_snp" },
  stack: { name: "stack@1.0", module: "dev_stack" },
  structured: { name: "structured@1.0", module: "dev_codec_structured" },
  "test-device": { name: "test-device@1.0", module: "dev_test" },
  volume: { name: "volume@1.0", module: "dev_volume" },
  wasi: { name: "wasi@1.0", module: "dev_wasi" },
  "wasm-64": { name: "wasm-64@1.0", module: "dev_wasm" },
  wao: { name: "wao@1.0", module: "dev_wao" },
}
